protocols = imap
listen = *
disable_plaintext_auth = no
auth_mechanisms = plain login
mail_privileged_group = vmail
mail_uid = vmail
mail_gid = vmail
mail_location = maildir:/var/mail/vhosts/%n/Maildir

passdb {
  driver = passwd-file
  args = scheme=PLAIN username_format=%n /etc/dovecot/users
}

userdb {
  driver = passwd-file
  args = username_format=%n /etc/dovecot/users
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

service auth {
  unix_listener auth-userdb {
    mode = 0600
    user = vmail
    group = vmail
  }
}

log_path = /dev/stderr
info_log_path = /dev/stdout
